### PR TITLE
chore: Replace reactjs.org to ja.reactjs.org in configuration files

### LINKED ISSUE #7: Update domain settings in package.json and JavaScript code base
[low priority]
Domain settings written in package.json etc are left as original documents, so we need to improve.

### PR DESCRIPTION
**Pull request by potato4d**
This PR is resolve #7 

## ToDos

- [x] complete Decide on subdomain https://github.com/reactjs/ja.reactjs.org/issues/1 issue
- [x] [For LICENSE](https://github.com/reactjs/ja.reactjs.org/blob/master/README.md#license), decide whether to continue using open-source-explorer's

### CODE REVIEW

**Comment by koba04** [comment]
#1 has been resolved, so we use `ja` as our subdomain.
What license should we take? Is it better to keep the same license with reactjs.org?

**Comment by gaearon** [comment]
The license should be the same.

**Comment by potato4d** [comment]
Thank you for your reply.
Even for quick follow up, we will keep the license as a link to the origin docs.
https://github.com/reactjs/ja.reactjs.org/blob/master/README.md#license

@gaearon
that's fine?

**Comment by tesseralis** [comment]
There's also changing it to `lang="ja"` in html.js, though I don't know if you want that in a separate PR.

**Comment by potato4d** [comment]
@tesseralis 
I have done it now.

@koba04 
Please review :pray:

**Comment by potato4d** [comment]
ちょっと rebase するのでお待ちを 🙇

**Comment by potato4d** [comment]
@koba04 
みてもらえるとー

**Pull request merged**
