### PR TITLE
Add original English explicit heading IDs to everything

### PR DESCRIPTION
**Pull request by tesseralis**
@smikitky since I was the one who didn't figure this out until late I figured it was my responsibility to fix it :P

### CODE REVIEW

**Comment by tesseralis** [comment]
@smikitky thanks for finding all those errors >_< How are you able to find them? Whenever I try to look at the diff on github everything just freezes up!

**Comment by smikitky** [comment]
Oh, thank you. Did you use some script to do this?

I removed one conflict and one punctuation error.

Textlint is complaining because we expect *fullwidth* space after a fullwidth exclamation mark:

```
## 始めましょう！ {#lets-get-started}
                ^
```

But I believe this is an error on the textlint's side. We may have to disable this rule temporarily because this should be merged promptly. @potato4d @koba04 What do you think?

**Comment by smikitky** [comment]
@tesseralis I'm using vscode-pull-request to check the diff on my PC!

**Comment by tesseralis** [comment]
I did use some script to do it 😛

Also I should check vscode-pull-request! Thanks for being on top of this as always 🙏

**Comment by smikitky** [comment]
I took the liberty to disable the two textlint rules that were causing trouble. These rules has not been working correctly anyway, and we should introduce our own rule. (#20)

**Comment by tesseralis** [comment]
@smikitky It's very important that we *don't* do a squash commit here or else git won't register the original commits and doing another sync will cause errors.

**Comment by potato4d** [comment]
@smikitky 

> But I believe this is an error on the textlint's side. We may have to disable this rule temporarily because this should be merged promptly. @potato4d @koba04 What do you think?

I think there is no problem.

**Pull request merged**
