### PR TITLE
Sync original

### PR DESCRIPTION
**Pull request by tesseralis**
Doing this manually since there's a ton of commits.

The only page that has interfering translations is `hooks-intro.md`. It seems like the `git merge` is pretty smart about only creating a conflict where the english text has changed!

https://github.com/reactjs/ja.reactjs.org/pull/91/files#diff-daed9eb3a7702fb9fe0397b0f613d4faL8

### CODE REVIEW

**Comment by smikitky** [comment]
Wow, I was expecting something very tedious, but there are only four conflicts and all of them are fairly easy to resolve :)

So should I directly push to this branch to resolve conflicts?

**Comment by tesseralis** [comment]
Haha, the spanish fork translated more hooks articles so they have more conflicts :P

Just direct push to the branch!

**Comment by smikitky** [comment]
Done!

Actually this merge has changes that involve several ongoing PRs, but I'll take care of notifying the translators.

**Comment by smikitky** [comment]
@koba04 @potato4d Can either of you take a brief look? The only four conflicts have been resolved in 566d932e7bc3c6859f8b5839325de5782e1a6267, and everything else seems to have been automatically merged.

**Comment by koba04** [comment]
@smikitky I think it shouldn't squash-merge. it should keep the original commits.

**Comment by smikitky** [comment]
Okay, I re-enabled merge commits.

**Comment by smikitky** [comment]
@koba04 Could you approve? We should merge this PR before @takanorip and I can update the corresponding PRs.

**Comment by koba04** [comment]
@smikitky OK, I'll review this soon 🚀

**Comment by koba04** [comment]
done

**Pull request merged**
